### ISSUE TITLE
BarGraph elements

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/sim_platform#14]
Different types of charts, along with their filter and update actions.
- [ ] Maps
<img width="481" alt="capture d ecran 2019-02-11 a 13 29 39 copie" src="https://user-images.githubusercontent.com/1546847/52563391-8e5fd180-2e01-11e9-89c7-5b8ab5ebe513.png">

- [ ] Bars
<img width="787" alt="capture d ecran 2019-02-11 a 13 33 22" src="https://user-images.githubusercontent.com/1546847/52563421-a5062880-2e01-11e9-9c51-71d8b92800ee.png">

- [ ] Donuts
<img width="145" alt="capture d ecran 2019-02-11 a 13 33 27" src="https://user-images.githubusercontent.com/1546847/52563434-ac2d3680-2e01-11e9-86a1-f44354e83263.png">

**Comment by ghost** [comment]
**Reminder**: 

Please ensure _Qt Charts_ component is added.

![Qt charts - add component](https://user-images.githubusercontent.com/17321286/57455109-b200af80-726a-11e9-85ed-5bc76908a4a8.jpg)

**Comment by HaseebAhmad23** [comment]
How I can access this window?
________________________________

**Comment by ghost** [comment]
Since we discussed this in person. Here's the info for someone watching this thread.

It is part of _Qt_ installation process. In _Windows_, go to _Control Panel_ and select _uninstall programs_ then click on _Qt_. Next, select _uninstall_ and then further in the process, it asks to _add or remove components_ as part of _Qt maintain_ process instead of removing all components to uninstall.

**Comment by HaseebAhmad23** [comment]
![Bar](https://user-images.githubusercontent.com/18243096/58385271-ebb51280-7fed-11e9-8195-56617f6e74be.PNG)

**Comment by nguyenLisa** [comment]
Bar graph done. Pausing the other elements for now.  b8d3da4
